<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>导入客户 - Shopify 邮件营销</title><c:set var="ctx" value="${pageContext.request.contextPath}"/>
<link rel="stylesheet" href="${ctx}/baseui/static/h-ui/css/H-ui.min.css"><link rel="stylesheet" href="${ctx}/baseui/static/h-ui.admin/css/H-ui.admin.css"><link rel="stylesheet" href="${ctx}/baseui/lib/font-awesome-4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="${ctx}${uiAssetBase}/css/dashboard.css?v=20260918-import-layout">
</head><body class="shopify-console"><%@ include file="fragments/header.jspf" %><div class="console-layout"><%@ include file="fragments/navigation.jspf" %>
<main class="console-main"><section class="page-heading"><div><p class="eyebrow">导入客户</p></div></section>
<c:if test="${not empty successMessage}"><div class="flash-message success"><i class="fa fa-check-circle"></i><c:out value="${successMessage}"/></div></c:if><c:if test="${not empty errorMessage}"><div class="flash-message danger"><i class="fa fa-exclamation-circle"></i><c:out value="${errorMessage}"/></div></c:if>
<section class="content-section"><div class="section-heading"><div><h2>上传文件</h2><p>支持 UTF-8 CSV 或 XLSX，最大 64 MiB；第一列 firstName，第二列 lastName，第三列邮件地址，首行为标题。</p></div><div class="section-heading-actions"><span class="template-download-status" data-template-download-status role="status" aria-live="polite" hidden></span><a class="action-button" href="${ctx}/customers/imports/template" download data-template-download><i class="fa fa-download"></i>下载导入模板</a></div></div>
<c:choose><c:when test="${empty selectedShop}"><div class="empty-state"><i class="fa fa-lock"></i><strong>没有可用店铺</strong></div></c:when><c:when test="${not canManageCustomers}"><div class="system-notice"><i class="fa fa-eye"></i><div><strong>当前角色仅可查看导入记录</strong><p>只有 OWNER、ADMIN 或 MARKETER 可以创建客户导入任务。</p></div></div></c:when><c:otherwise><form class="workspace-form" method="post" enctype="multipart/form-data" action="${ctx}/customers/imports" data-customer-import-form><input type="hidden" name="shop" value="${selectedShop}"><div class="form-grid customer-import-fields"><label><span>客户文件</span><input type="file" name="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></label><label><span>导入订阅状态</span><small>SUBSCRIBED 表示操作人员确认客户已同意邮件营销</small><select name="consentState" required><option value="NOT_SUBSCRIBED" selected>NOT_SUBSCRIBED（未明确订阅）</option><option value="SUBSCRIBED">SUBSCRIBED（已确认订阅）</option></select></label><label><span>本批次客户标签</span><small>不填写时默认使用“导入客户”</small><input type="text" name="customerTag" maxlength="100" placeholder="导入客户"></label><div class="form-actions customer-import-submit-actions"><span class="customer-import-submit-status" data-customer-import-submit-status role="status" aria-live="polite" hidden></span><button class="primary-button" type="submit" data-customer-import-submit><i class="fa fa-upload" data-customer-import-submit-icon></i><span data-customer-import-submit-label>开始导入</span></button></div></div></form></c:otherwise></c:choose></section>
<section class="content-section spaced-section"><div class="section-heading"><div><h2>导入记录</h2><p hidden>作业每 500 行提交一次，可在服务重启后从断点继续。</p></div><span class="section-count">共 <c:out value="${importPage.total}"/> 条</span></div>
<c:choose><c:when test="${empty importJobs}"><div class="empty-state"><i class="fa fa-file-excel-o"></i><strong>暂无导入记录</strong></div></c:when><c:otherwise><div class="table-wrap"><table class="status-table wide-table"><thead><tr><th>文件</th><th>标签</th><th>状态</th><th>已处理 / 总行数</th><th>新增</th><th>合并</th><th>无效</th><th>创建时间</th><th>操作</th></tr></thead><tbody><c:forEach items="${importJobs}" var="job"><tr><td><strong><c:out value="${job.originalFilename}"/></strong><span class="cell-note"><c:out value="${job.jobId}"/></span></td><td><span class="status-pill neutral"><c:out value="${job.customerTag}"/></span></td><td><span class="status-pill"><c:out value="${job.status}"/></span><c:if test="${job.status eq 'FAILED' and not empty job.errorSummary}"><span class="cell-note"><c:out value="${job.errorSummary}"/></span></c:if></td><td><c:out value="${job.processedCount}"/> / <c:out value="${job.totalRows}" default="-"/></td><td><c:out value="${job.insertedCount}"/></td><td><c:out value="${job.mergedCount}"/></td><td><c:out value="${job.invalidCount}"/></td><td><time data-browser-time="<c:out value='${job.createdAt}'/>" data-browser-time-format="date-time" datetime="<c:out value='${job.createdAt}'/>"><c:out value="${job.createdAt}"/></time></td><td data-import-job-actions><c:if test="${job.invalidCount gt 0}"><a class="action-button" href="${ctx}/customers/imports?shop=${selectedShop}&amp;jobId=${job.jobId}&amp;page=${importPage.page}"><i class="fa fa-exclamation-triangle"></i>查看错误</a> </c:if><c:if test="${canExportCustomerData}"><c:if test="${job.resultStatus eq 'READY'}"><a class="action-button" data-import-result-download href="${ctx}/customers/imports/result?shop=${selectedShop}&amp;jobId=${job.jobId}"><i class="fa fa-download"></i>下载结果</a><span class="cell-note"><c:out value="${job.requestedConsentState}"/></span></c:if></c:if><c:if test="${job.invalidCount le 0 and job.resultStatus ne 'READY'}"><span class="cell-note">—</span></c:if></td></tr></c:forEach></tbody></table></div><c:url var="importPreviousUrl" value="/customers/imports"><c:param name="shop" value="${selectedShop}"/><c:param name="page" value="${importPage.page - 1}"/></c:url><c:url var="importNextUrl" value="/customers/imports"><c:param name="shop" value="${selectedShop}"/><c:param name="page" value="${importPage.page + 1}"/></c:url><div class="pagination-bar"><c:if test="${importPage.hasPrevious}"><a class="action-button" href="${importPreviousUrl}">上一页</a></c:if><span>第 <c:out value="${importPage.page}"/> / <c:out value="${importPage.totalPages}"/> 页</span><c:if test="${importPage.hasNext}"><a class="action-button" href="${importNextUrl}">下一页</a></c:if></div></c:otherwise></c:choose></section>
<c:if test="${not empty selectedImportJobId}"><section class="content-section"><div class="section-heading"><div><h2>错误样本</h2><p>作业 <c:out value="${selectedImportJobId}"/>，最多显示前 100 条。</p></div></div><c:choose><c:when test="${empty importErrors}"><div class="empty-state"><strong>没有错误记录</strong></div></c:when><c:otherwise><div class="table-wrap"><table class="status-table"><thead><tr><th>行号</th><th>名称</th><th>邮件地址</th><th>原因</th></tr></thead><tbody><c:forEach items="${importErrors}" var="error"><tr><td><c:out value="${error.rowNumber}"/></td><td><c:out value="${error.rawName}"/></td><td><c:out value="${error.rawEmail}"/></td><td><c:out value="${error.errorMessage}"/></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose></section></c:if>
<script>(()=>{const templateDownload=document.querySelector('[data-template-download]');const templateDownloadStatus=document.querySelector('[data-template-download-status]');if(templateDownload&&templateDownloadStatus){let resetTimer;templateDownload.addEventListener('click',()=>{window.clearTimeout(resetTimer);templateDownloadStatus.hidden=false;templateDownloadStatus.textContent='正在下载导入模板…';resetTimer=window.setTimeout(()=>{templateDownloadStatus.textContent='下载已开始，请查看浏览器下载记录';},600);});}const customerImportForm=document.querySelector('[data-customer-import-form]');const customerImportSubmit=document.querySelector('[data-customer-import-submit]');const customerImportSubmitStatus=document.querySelector('[data-customer-import-submit-status]');const customerImportSubmitIcon=document.querySelector('[data-customer-import-submit-icon]');const customerImportSubmitLabel=document.querySelector('[data-customer-import-submit-label]');if(customerImportForm&&customerImportSubmit&&customerImportSubmitStatus){customerImportForm.addEventListener('submit',()=>{customerImportSubmit.disabled=true;customerImportSubmit.setAttribute('aria-busy','true');customerImportSubmitStatus.hidden=false;customerImportSubmitStatus.textContent='正在上传并创建导入任务…';if(customerImportSubmitIcon)customerImportSubmitIcon.className='fa fa-circle-o-notch fa-spin';if(customerImportSubmitLabel)customerImportSubmitLabel.textContent='正在导入…';});}})();</script>
</main></div></body></html>
