<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>效果分析 - Shopify 邮件营销</title><c:set var="ctx" value="${pageContext.request.contextPath}"/>
    <link rel="stylesheet" href="${ctx}/baseui/static/h-ui/css/H-ui.min.css"><link rel="stylesheet" href="${ctx}/baseui/static/h-ui.admin/css/H-ui.admin.css"><link rel="stylesheet" href="${ctx}/baseui/lib/font-awesome-4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="${ctx}${uiAssetBase}/css/dashboard.css?v=20260923-report-cockpit">
</head>
<body class="shopify-console"><%@ include file="fragments/header.jspf" %><div class="console-layout"><%@ include file="fragments/navigation.jspf" %>
<main class="console-main report-main">
<link rel="stylesheet" href="${ctx}${uiAssetBase}/css/reports-analytics.css?v=20260923-report-cockpit-v2">
<style>.report-kpi > div{min-width:0}.report-kpi > div > small{display:block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}</style>
<c:url var="dayUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="day"/></c:url><c:url var="weekUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="week"/></c:url><c:url var="monthUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="month"/></c:url><c:url var="yearUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="year"/></c:url>

<section class="report-hero"><div class="report-hero-copy"><p class="eyebrow">效果分析</p><h1>营销数据洞察</h1><p>从邮件触达到成交结果，集中观察当前店铺的营销效率与经营趋势。</p><span class="report-range"><i class="fa fa-calendar-check-o"></i><c:out value="${analytics.period.rangeLabel}"/> · <c:out value="${analytics.startDate}"/> 至 <c:out value="${analytics.endDate}"/></span></div><nav class="report-period-switch" aria-label="统计周期"><a data-report-period="day" class="${analytics.period.key eq 'day' ? 'active' : ''}" href="${dayUrl}"><strong>日</strong><span>近 30 日</span></a><a data-report-period="week" class="${analytics.period.key eq 'week' ? 'active' : ''}" href="${weekUrl}"><strong>周</strong><span>近 12 周</span></a><a data-report-period="month" class="${analytics.period.key eq 'month' ? 'active' : ''}" href="${monthUrl}"><strong>月</strong><span>近 12 月</span></a><a data-report-period="year" class="${analytics.period.key eq 'year' ? 'active' : ''}" href="${yearUrl}"><strong>年</strong><span>近 5 年</span></a></nav></section>

<section class="report-kpi-grid" aria-label="综合效果指标">
<article class="report-kpi sent"><span class="report-kpi-icon"><i class="fa fa-paper-plane"></i></span><div><small>发送量</small><strong><fmt:formatNumber value="${analytics.totals.sent}"/></strong><em>进入邮件投递流程</em></div></article>
<article class="report-kpi delivered"><span class="report-kpi-icon"><i class="fa fa-check-circle"></i></span><div><small>送达率</small><strong><fmt:formatNumber value="${analytics.totals.deliveryRate}" minFractionDigits="1" maxFractionDigits="1"/>%</strong><em><fmt:formatNumber value="${analytics.totals.delivered}"/> 封已送达</em></div></article>
<article class="report-kpi opened"><span class="report-kpi-icon"><i class="fa fa-envelope-open"></i></span><div><small>打开率</small><strong><fmt:formatNumber value="${analytics.totals.openRate}" minFractionDigits="1" maxFractionDigits="1"/>%</strong><em><fmt:formatNumber value="${analytics.totals.opened}"/> 封邮件已打开</em></div></article>
<article class="report-kpi clicked"><span class="report-kpi-icon"><i class="fa fa-hand-pointer-o"></i></span><div><small>点击率</small><strong><fmt:formatNumber value="${analytics.totals.clickRate}" minFractionDigits="1" maxFractionDigits="1"/>%</strong><em><fmt:formatNumber value="${analytics.totals.clicked}"/> 封邮件已点击</em></div></article>
<article class="report-kpi orders"><span class="report-kpi-icon"><i class="fa fa-shopping-bag"></i></span><div><small>归因订单数</small><strong><fmt:formatNumber value="${analytics.totals.orders}"/></strong><em>营销活动 / 自动营销</em></div></article>
<article class="report-kpi revenue"><span class="report-kpi-icon"><i class="fa fa-line-chart"></i></span><div><small>归因订单金额<c:if test="${not analytics.currencyMixed and not empty analytics.currency}">（<c:out value="${analytics.currency}"/>）</c:if></small><strong><c:choose><c:when test="${analytics.currencyMixed or empty analytics.currency or empty analytics.totals.orderAmount}">--</c:when><c:otherwise><fmt:formatNumber value="${analytics.totals.orderAmount}" minFractionDigits="2" maxFractionDigits="2"/></c:otherwise></c:choose></strong><em>营销活动 / 自动营销归因净额</em></div></article>
<article class="report-kpi attributed"><span class="report-kpi-icon"><i class="fa fa-bullseye"></i></span><div><small>GA4 归因订单金额</small><strong><c:choose><c:when test="${!analytics.ga4Available or analytics.ga4CurrencyMixed or empty analytics.ga4Currency or empty analytics.totals.ga4Revenue}">--</c:when><c:otherwise><fmt:formatNumber value="${analytics.totals.ga4Revenue}" minFractionDigits="2" maxFractionDigits="2"/></c:otherwise></c:choose></strong><em>GA4 邮件来源购买收入</em></div></article>
</section>

<div data-report-series hidden data-currency="<c:out value='${analytics.currency}'/>" data-ga4-currency="<c:out value='${analytics.ga4Currency}'/>"><c:forEach items="${analytics.points}" var="point"><i data-label="<c:out value='${point.label}'/>" data-sent="${point.sent}" data-delivered="${point.delivered}" data-opened="${point.opened}" data-clicked="${point.clicked}" data-orders="${point.orders}" data-revenue="${point.orderAmount}" data-ga4="${point.ga4Revenue}"></i></c:forEach></div>

<section class="report-chart-grid"><article class="report-panel report-chart-panel"><header><div><span class="report-panel-kicker">触达与互动</span><h2>邮件效果趋势</h2></div><div class="report-legend"><span class="sent">发送</span><span class="delivered">送达</span><span class="opened">打开</span><span class="clicked">点击</span></div></header><div class="report-chart-wrap"><svg data-engagement-chart viewBox="0 0 760 310" role="img" aria-label="邮件发送、送达、打开和点击趋势"></svg></div></article><article class="report-panel report-chart-panel"><header><div><span class="report-panel-kicker">成交结果</span><h2>归因订单与收入趋势</h2></div><div class="report-legend"><span class="orders">归因订单</span><span class="revenue">归因净额</span><span class="ga4">GA4 归因金额</span></div></header><div class="report-chart-wrap"><svg data-commerce-chart viewBox="0 0 760 310" role="img" aria-label="归因订单、归因净额和 GA4 归因金额趋势"></svg></div></article></section>

<section class="report-panel report-funnel-panel"><header><div><span class="report-panel-kicker">转化路径</span><h2>效果漏斗</h2></div><p hidden>打开数据受邮箱隐私代理影响，仅作为趋势参考</p></header><div class="report-funnel"><article style="--funnel-width:100%"><span><i class="fa fa-paper-plane"></i>发送</span><strong><fmt:formatNumber value="${analytics.totals.sent}"/></strong><em>100%</em></article><article style="--funnel-width:86%"><span><i class="fa fa-check-circle"></i>送达</span><strong><fmt:formatNumber value="${analytics.totals.delivered}"/></strong><em><fmt:formatNumber value="${analytics.totals.deliveryRate}" minFractionDigits="1" maxFractionDigits="1"/>%</em></article><article style="--funnel-width:72%"><span><i class="fa fa-envelope-open"></i>打开</span><strong><fmt:formatNumber value="${analytics.totals.opened}"/></strong><em><fmt:formatNumber value="${analytics.totals.openRate}" minFractionDigits="1" maxFractionDigits="1"/>%</em></article><article style="--funnel-width:58%"><span><i class="fa fa-hand-pointer-o"></i>点击</span><strong><fmt:formatNumber value="${analytics.totals.clicked}"/></strong><em><fmt:formatNumber value="${analytics.totals.clickRate}" minFractionDigits="1" maxFractionDigits="1"/>%</em></article></div></section>

<section class="report-panel report-period-detail"><details><summary><div><span class="report-panel-kicker">时间明细</span><h2><c:out value="${analytics.period.granularityLabel}"/>数据</h2></div><i class="fa fa-chevron-down"></i></summary><div class="table-wrap"><table class="status-table wide-table"><thead><tr><th>周期</th><th>发送</th><th>送达</th><th>打开</th><th>点击</th><th>归因订单</th><th>归因净额</th><th>GA4 归因金额</th></tr></thead><tbody><c:forEach items="${analytics.points}" var="point"><tr><td><strong><c:out value="${point.label}"/></strong></td><td><fmt:formatNumber value="${point.sent}"/></td><td><fmt:formatNumber value="${point.delivered}"/></td><td><fmt:formatNumber value="${point.opened}"/></td><td><fmt:formatNumber value="${point.clicked}"/></td><td><fmt:formatNumber value="${point.orders}"/></td><td><c:choose><c:when test="${analytics.currencyMixed}">--</c:when><c:otherwise><fmt:formatNumber value="${point.orderAmount}" minFractionDigits="2" maxFractionDigits="2"/></c:otherwise></c:choose></td><td><c:choose><c:when test="${!analytics.ga4Available or analytics.ga4CurrencyMixed}">--</c:when><c:otherwise><fmt:formatNumber value="${point.ga4Revenue}" minFractionDigits="2" maxFractionDigits="2"/></c:otherwise></c:choose></td></tr></c:forEach></tbody></table></div></details></section>

<section class="content-section report-ledger"><details class="report-ledger-details"><summary class="section-heading"><div><h2>营销活动台账</h2><p>按活动核对受众、投递互动和归因收入</p></div><span class="section-count"><c:out value="${reportPage.total}"/> 个</span><i class="fa fa-chevron-down report-ledger-toggle" aria-hidden="true"></i></summary><div class="report-ledger-body"><c:choose><c:when test="${empty reports}"><div class="empty-state"><i class="fa fa-line-chart"></i><strong>暂无报表数据</strong><span>活动开始发送并收到邮件服务商反馈后，这里会自动汇总。</span></div></c:when><c:otherwise><div class="table-wrap"><table class="status-table wide-table"><thead><tr><th>活动</th><th>状态</th><th>总用户数</th><th>发送数</th><th>送达</th><th>打开</th><th>点击</th><th>发送失败</th><th>投诉</th><th>退订</th><th>收入</th></tr></thead><tbody><c:forEach items="${reports}" var="report"><tr><td><strong><c:out value="${report.campaignName}"/></strong></td><td><span class="status-pill neutral"><c:out value="${report.status}"/></span></td><td><c:out value="${report.audienceCount}"/></td><td><c:out value="${report.accepted}"/></td><td><c:out value="${report.delivered}"/></td><td><c:out value="${report.opened}"/></td><td><c:out value="${report.clicked}"/></td><td><c:out value="${report.hardBounced}"/></td><td><c:out value="${report.complained}"/></td><td><c:out value="${report.unsubscribed}"/></td><td><c:out value="${report.netRevenue}"/></td></tr></c:forEach></tbody></table></div><c:url var="reportPreviousUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="${analytics.period.key}"/><c:param name="page" value="${reportPage.page - 1}"/></c:url><c:url var="reportNextUrl" value="/reports"><c:param name="shop" value="${selectedShop}"/><c:param name="period" value="${analytics.period.key}"/><c:param name="page" value="${reportPage.page + 1}"/></c:url><div class="pagination-bar"><c:if test="${reportPage.hasPrevious}"><a class="action-button" href="${reportPreviousUrl}">上一页</a></c:if><span>第 <c:out value="${reportPage.page}"/> / <c:out value="${reportPage.totalPages}"/> 页</span><c:if test="${reportPage.hasNext}"><a class="action-button" href="${reportNextUrl}">下一页</a></c:if></div></c:otherwise></c:choose></section>
<script src="${ctx}/shopify/js/reports-analytics.js?v=20261003-attributed-orders"></script>
</main></div></body></html>
