<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>商品详情 - Shopify 邮件营销</title><c:set var="ctx" value="${pageContext.request.contextPath}"/><link rel="stylesheet" href="${ctx}/baseui/static/h-ui/css/H-ui.min.css"><link rel="stylesheet" href="${ctx}/baseui/static/h-ui.admin/css/H-ui.admin.css"><link rel="stylesheet" href="${ctx}/baseui/lib/font-awesome-4.7.0/css/font-awesome.min.css"><link rel="stylesheet" href="${ctx}${uiAssetBase}/css/dashboard.css"></head>
<body class="shopify-console"><c:url var="productListUrl" value="/products"><c:param name="shop" value="${selectedShop}"/><c:param name="q" value="${param.q}"/><c:param name="page" value="${param.page}"/><c:param name="size" value="${param.size}"/></c:url><%@ include file="fragments/header.jspf" %><div class="console-layout"><%@ include file="fragments/navigation.jspf" %><main class="console-main">
<section class="page-heading"><div><p class="eyebrow"><a href="${productListUrl}"><i class="fa fa-arrow-left"></i> 返回商品列表</a></p><h1><c:out value="${productDetail.product.title}"/></h1><p><c:out value="${productDetail.product.vendor}"/> · <c:out value="${productDetail.product.productType}"/> · <c:out value="${productDetail.product.sourceId}"/></p></div><span class="status-pill"><c:out value="${productDetail.product.status}"/></span></section>
<section class="content-section product-profile"><c:choose><c:when test="${not empty productDetail.content.imageUrl}"><img class="product-hero-image" src="<c:out value='${productDetail.content.imageUrl}'/>" alt="<c:out value='${productDetail.content.imageAlt}' default='商品图片'/>"></c:when><c:otherwise><div class="product-image-empty"><i class="fa fa-image"></i><span>暂无商品图片</span></div></c:otherwise></c:choose><div class="product-profile-copy"><h2>商品介绍</h2><c:choose><c:when test="${not empty productDetail.content.descriptionHtml}"><div class="product-description"><c:out value="${productDetail.content.descriptionHtml}" escapeXml="false"/></div></c:when><c:otherwise><p class="muted-text">暂无商品介绍</p></c:otherwise></c:choose><dl class="product-meta"><dt>商品链接</dt><dd><a class="table-link" href="<c:out value='${productDetail.content.productUrl}'/>" target="_blank" rel="noopener noreferrer"><c:out value="${productDetail.content.productUrl}"/></a></dd><dt>Handle</dt><dd><c:out value="${productDetail.content.handle}" default="-"/></dd><dt>商品标签</dt><dd><c:out value="${productDetail.content.tags}" default="-"/></dd><dt>创建时间</dt><dd><time data-browser-time="<c:out value='${productDetail.content.createdAt}'/>" datetime="<c:out value='${productDetail.content.createdAt}'/>"><c:out value="${productDetail.content.createdAt}" default="-"/></time></dd><dt>更新时间</dt><dd><time data-browser-time="<c:out value='${productDetail.content.updatedAt}'/>" datetime="<c:out value='${productDetail.content.updatedAt}'/>"><c:out value="${productDetail.content.updatedAt}" default="-"/></time></dd></dl></div></section>
<section class="detail-grid"><div class="detail-stat"><span>价格区间</span><strong><c:out value="${productDetail.product.minPrice}"/> - <c:out value="${productDetail.product.maxPrice}"/></strong></div><div class="detail-stat"><span>总库存</span><strong><c:out value="${productDetail.product.inventoryQuantity}"/></strong></div><div class="detail-stat"><span>成交订单</span><strong><c:out value="${productDetail.product.orderCount}"/></strong></div><div class="detail-stat"><span>销售额</span><strong><c:out value="${productDetail.product.currency}"/> <c:out value="${productDetail.product.grossSales}"/></strong></div></section>
<section class="content-section spaced-section"><div class="section-heading"><div><h2>商品变体</h2><p>价格、SKU 与库存明细</p></div></div><div class="table-wrap"><table class="status-table"><thead><tr><th>变体</th><th>SKU</th><th>条码</th><th>价格</th><th>对比价</th><th>库存</th></tr></thead><tbody><c:forEach items="${productDetail.variants}" var="variant"><tr><td><c:out value="${variant.title}"/></td><td><c:out value="${variant.sku}" default="-"/></td><td><c:out value="${variant.barcode}" default="-"/></td><td><c:out value="${variant.price}"/></td><td><c:out value="${variant.compareAtPrice}" default="-"/></td><td><c:out value="${variant.inventoryQuantity}"/></td></tr></c:forEach></tbody></table></div></section>
<section class="content-section spaced-section"><div class="section-heading"><div><h2>关联订单</h2><p>最近包含该商品的订单</p></div></div><div class="table-wrap"><table class="status-table"><thead><tr><th>订单</th><th>商品数量</th><th>财务状态</th><th>履约状态</th><th>订单金额</th><th>成交时间</th></tr></thead><tbody><c:forEach items="${productDetail.recentOrders}" var="order"><tr><td><strong><c:out value="${order.orderName}"/></strong></td><td><c:out value="${order.productQuantity}"/></td><td><c:out value="${order.financialStatus}"/></td><td><c:out value="${order.fulfillmentStatus}"/></td><td><c:out value="${order.currency}"/> <c:out value="${order.totalPrice}"/></td><td><time data-browser-time="<c:out value='${order.processedAt}'/>" datetime="<c:out value='${order.processedAt}'/>"><c:out value="${order.processedAt}"/></time></td></tr></c:forEach></tbody></table></div></section>
</main></div></body></html>
